C: 1.0
break_ties: false
cache_size: 200
class_weight: null
coef0: 0.0
decision_function_shape: ovr
degree: 3
gamma: scale
kernel: rbf
max_iter: -1
probability: false
random_state: null
shrinking: true
tol: 0.001
verbose: false
